[package]
name = "skia-safe"
version = "0.8.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[features]
default = []
vulkan = ["skia-bindings/vulkan"]
svg = ["skia-bindings/svg"]

[dependencies]
bitflags = "1.0.4"
skia-bindings = { path = "../skia-bindings" }
lazy_static = "1.3.0"

[dev-dependencies]
# for skia-org
offscreen_gl_context = "0.22.0"
gleam = "0.6.16"
clap = "2.33.0"
# Entry.try_enumerate_instance_version will be available beginning with 0.29
ash = { git = "https://github.com/MaikKlein/ash", rev = "775a7d035d836559a30a9ee63a0e726d7b9118f4"}
