stages:

- stage: 'Build'
  jobs:
  - template: 'azure-pipelines-template.yml'
    parameters:
      platform: 'Linux'
      image: 'ubuntu-16.04'

  - template: 'azure-pipelines-template.yml'
    parameters:
      platform: 'macOS'
      image: 'macOS-10.14'

  - template: 'azure-pipelines-template.yml'
    parameters:
      platform: 'Windows'
      image: 'vs2017-win2016'

- stage: 'Package'
  condition: and(succeeded(), eq(variables['build.SourceBranchName'], 'master'))
  jobs:
  - job:
    pool:
      vmImage: ubuntu-16.04
    variables:
      rust_backtrace: 1

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.x'
        addToPath: true
        architecture: 'x64'

    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'

    - script: |
        rustc -Vv
        cargo -V
      displayName: 'Print versions'

    - bash: |
        set -e
        cd skia-bindings && cargo package -vv --target-dir "$(Build.ArtifactStagingDirectory)"
      displayName: 'Package and Verify skia-bindings'

    # TODO: why does this fail with
    # error: 1 files in the working directory contain changes that were not yet committed into git:
    #   src/prelude.rs
    # to proceed despite this, pass the `--allow-dirty` flag
    # TODO: find a better way to extract the GITHUB_RELEASE_TAG
    - bash: |
        set -e
        cd skia-safe && cargo package -vv --no-verify --allow-dirty --target-dir "$(Build.ArtifactStagingDirectory)"
        export GITHUB_RELEASE_TAG=$(cd "$(Build.ArtifactStagingDirectory)/package" && find skia-safe-*.crate | cut -d'-' -f3 | cut -d'.' -f1-3)
        echo "##vso[task.setvariable variable=GITHUB_RELEASE_TAG;]${GITHUB_RELEASE_TAG}"
      displayName: 'Package skia-safe'

    - task: GithubRelease@0
      displayName: 'Release to GitHub rust-skia/rust-skia'
      inputs:
        action: 'edit'
        gitHubConnection: 'rust-skia-github-connection'
        repositoryName: 'rust-skia/rust-skia'
        tagSource: 'manual'
        target: 'master'
        tag: '$(GITHUB_RELEASE_TAG)'
        assets: '$(Build.ArtifactStagingDirectory)/package/*.crate'
        assetUploadMode: 'replace'
        isPreRelease: true
        addChangeLog: false
