[package]
name = "skia-bindings"
version = "0.8.0"
authors = ["LongYinan <lynweklm@gmail.com>", "Armin Sander <armin@replicator.org>"]
edition = "2018"
build = "build.rs"
links = "skia"
include = [ "Cargo.toml", "build.rs", "src/**/*.cpp", "src/lib.rs", "skia/include/**/*", "skia/src/**/*" ]

[features]
default = []
vulkan = []
svg = []

[dependencies]

[build-dependencies]
cc = "1.0.35"
bindgen = "0.49.0"
